### ISSUE TITLE
重複進入同篇文章 樓層錯誤問題

### ISSUE THREAD

**Issue by neji0924** [alan23273850/PttChrome-and-term.ptt.cc-Enhanced-Add-on#1]
如題

若先進別篇文章則不回有此問題

**Comment by alan23273850** [comment]
大大您好：

感謝您的提醒，那個其實不是別篇跟同篇的問題，是因為樓層數會在看板的時候歸零，原本需要 0.5 秒，而同篇進出的時距較短，就來不及歸零。

也因為大大提醒，我後來才發現時距是可以調整的，原本是 1 秒現在改為 0.1 秒，再發生同樣問題的機率便微乎其微。Greasy Fork 版本已經更新 v1.0.2，請重新下載，感謝您。

**Comment by alan23273850** [comment]
如果問題解決的話請幫我 close issue ～

**Comment by alan23273850** [comment]
大大您好：

我目前把程式改回與原作相同的架構了，現在的話讀取文章時不管怎麼往底部下拉都不會出錯，不用擔心速度的問題，請再度更新謝謝！
