### ISSUE TITLE
 版面層級 失敗範例

### ISSUE THREAD

**Issue by ingrid-z** [alan23273850/PttChrome-and-term.ptt.cc-Enhanced-Add-on#2]
在使用term.ptt.cc的情形下，隨機點了數個版面瀏覽測試推文樓層是否正常。
發現Hearthstone、IntlShopping、MobileComm是全文章失效無作用的。
但有極少數的例外，如下：（計數錯誤）
https://www.ptt.cc/bbs/MobileComm/M.1550725926.A.E0F.html
https://www.ptt.cc/bbs/MobileComm/M.1550835709.A.CEB.html

應該還有其他潛在版面也是全面無作用的只是尚未發現。

**Comment by alan23273850** [comment]
大大您好：

感謝告知，我剛剛用 avans 大的原版腳本去跑也發生一樣的狀況，其實還有我 GreasyFork 首頁提到的 Math、StupidClown 也有相同情況，不然我寄信給 avans 大問他看看是怎麼回事，不過這個 bug 可能不會那麼快修復。目前如果要維持正常功能的話可能要先請大大使用 PttChrome 了。

**Comment by alan23273850** [comment]
大大您好：

avans 大剛剛已經回覆我主要是因為 PTT 的網頁本身格式不只有一種，你可以發現發生問題的版面在推文的格式裡面 user id 後面的冒號都是對齊的，和其他版面的冒號緊接在 user id 後面有所不同，因為有兩種格式所以造成解析錯誤。

目前已經更新至 v1.0.3 了，請大大再次更新，謝謝！
