### ISSUE TITLE
點擊highlight同推文者 // 點擊推文者與滑鼠瀏覽衝突

### ISSUE THREAD

**Issue by ingrid-z** [alan23273850/PttChrome-and-term.ptt.cc-Enhanced-Add-on#3]
1.點擊highlight同推文者
看到您提及這功能，但在term.ptt.cc下怎麼點都沒有作用？（已關閉滑鼠瀏覽）

2.點擊推文者與滑鼠瀏覽衝突
開啟滑鼠瀏覽與點擊推文者出現選單，互相作用造成功能無法正常使用，
點擊推文者便會退出文章閱讀或跳上下頁。

有辦法在進入閱讀文章時overwrite滑鼠瀏覽的行為嗎？（或其他解決方案）
關掉滑鼠瀏覽再查詢感覺不太人性化？

另外@match（url）規則可以麻煩您修正嗎？
我查了violetmonkey的api發現@match 較 @include嚴謹，
而您在term.ptt.cc/*前面沒加https://
在使用violetmonkey下無作用，因match條件不對。

感謝您的付出。:)

**Comment by alan23273850** [comment]
謝謝大大指教～

1. 資訊太少無法幫忙 debug，我需要更多資訊，理論上應該要能正常執行。不過我想解釋因為 PttChrome 和 term.ptt.cc 網頁架構不同，所以呈現方式也不一樣，PttChrome 是整層樓變藍底，term.ptt.cc 只有 user id 部份加上淺綠底。

2. 這個我也有同感，目前我的 workaround 是要 highlight 的時候滑鼠可以稍微拖曳一小段，這樣頁面就不會跳動，點擊推文者的時候盡量靠右，以避免觸發上一頁。滑鼠右鍵會直接出現切換滑鼠瀏覽選項，對我來說還算過得去。預計之後會找時間更新 (不會那麼快)，如果更新的話我只會 disable 掉上下捲動這個不太實用的功能，回上一頁還是會保留 (或者同時讓點擊範圍往左靠)。

3. 預計下次更新的時候順便修正，大大目前可以先行修改，只要不做腳本更新就不會被洗掉。

**Comment by alan23273850** [comment]
大大您好：

現在修正過後的結果是當推文高亮發生的時候 javascript 會順勢把滑鼠訊號攔截以避免系統偵測到位置而進行跳轉，(換句話說高亮沒發生的時候滑鼠瀏覽就會正常運作)，其實只要一行 code 便可完成，由於我對 javascript 不太熟所以花了點時間。

match 規則也已經修正。關於原問題的 1. 大大可以再提供更多資訊。

版本更新 v1.0.4，請大大再試試看！謝謝大大指教～

**Comment by ingrid-z** [comment]
> _現在修正過後的結果是當推文高亮發生的時候` javascript 會順勢把滑鼠訊號攔截以避免系統偵測到位置而進行跳轉，(換句話說高亮沒發生的時候滑鼠瀏覽就會正常運作)，其實只要一行 code 便可完成，由於我對 javascript 不太熟所以花了點時間。_

我不太懂您的意思。您是指已修正了2.的問題嗎？
如果是這樣的話，似乎沒有修正。
[https://i.imgur.com/Tac8bEy.gifv](https://i.imgur.com/Tac8bEy.gifv)
註：這是在PttChrome下錄製。

> _match 規則也已經修正。關於原問題的 1. 大大可以再提供更多資訊。_

1.的問題
[https://i.imgur.com/sP58qaB.gifv](https://i.imgur.com/sP58qaB.gifv)
註：這是在PttChrome下錄製。

滑鼠遊標停頓，代表在點擊。（點擊效果無錄製）

**Comment by alan23273850** [comment]
這是我在 Chrome Version 72.0.3626.119 (Official Build) (64-bit) 底下開 PttChrome 的結果：https://imgur.com/Drw54V5

如果用 Chromium 改過來的瀏覽器像 Yandex 或 Cent 的話目前還有問題，他們和 Chrome 還是有差別，所以之後才會慢慢修復。如果大大是用 Chrome 瀏覽器的話可以報給我版本號讓我試試～

**Comment by ingrid-z** [comment]
Google Chrome
Version 72.0.3626.119 (Official Build) (64-bit)
同版本

**Comment by alan23273850** [comment]
經查證發現是我在第 739 行的 str 變數前面忘記加上 var 造成沒宣告就使用的錯誤，
(我不知道是原本就忘記加、還是某次修正之中不小心把它刪掉了)，
term.ptt.cc 的比對也從 match 改成 include，現在為 v1.0.6。

造成大大困擾深感抱歉，如果這次 OK 的話請回報一下讓我能 close issue，感謝～

**Comment by ingrid-z** [comment]
已正常作用。
GJ  💯

**Comment by alan23273850** [comment]
Great～ 謝謝大大指導

**Comment by ingrid-z** [comment]
> _term.ptt.cc 的比對也從 match 改成 include，現在為 v1.0.6。_

我會建議您避免使用 @include

[https://wiki.greasespot.net/Include_and_exclude_rules](https://wiki.greasespot.net/Include_and_exclude_rules)
如上GreaseSpot有提到 @include 比較舊且安全性沒 @match 好，所以建議改用 @match 。

如果我寫了一個符合 @include 網址條件的釣魚網頁，不知情的用戶連上後，
跟原始ptt送出一樣指令給客戶端，如果客戶端有使用自動登入，就....Booooom。

如果沒有相容性的問題，@include 儘量避免。
而且ptt連線全時只有用到一個網址，沒有子頁面的問題存在。

**Comment by alan23273850** [comment]
再次感謝指教～ 今天修的時候那個時候因故 match 無法成功才改成 include，
剛剛又嘗試了一下發現又可以用 match，已經修正成 v1.0.7 了。
